// Browser-only helpers for the change-request element picker. They run against
// the same-origin iframe's document, never the admin page itself.

const STABLE_DATA_ATTRIBUTES = ['data-testid', 'data-test', 'data-section', 'data-component']
const MAX_TARGET_TEXT = 500

function cssEscape(value: string): string {
  if (typeof CSS !== 'undefined' && typeof CSS.escape === 'function') return CSS.escape(value)
  return value.replace(/[^A-Za-z0-9_-]/g, (char) => `\\${char}`)
}

function isUnique(doc: Document, selector: string): boolean {
  try {
    return doc.querySelectorAll(selector).length === 1
  } catch {
    return false
  }
}

/** Ids generated by React (`:r1:`, `«r1»`) or numeric-only ids change between renders. */
function isStableId(id: string): boolean {
  return /^[A-Za-z][\w-]*$/.test(id) && !/^(?:radix|headlessui|react)-/.test(id)
}

/** A selector that identifies `el` on its own, if one exists. */
function anchorSelector(el: Element, doc: Document): string | null {
  if (el.id && isStableId(el.id)) {
    const selector = `#${cssEscape(el.id)}`
    if (isUnique(doc, selector)) return selector
  }

  for (const attribute of STABLE_DATA_ATTRIBUTES) {
    const value = el.getAttribute(attribute)
    if (value) {
      const selector = `[${attribute}="${value.replace(/["\\]/g, '\\$&')}"]`
      if (isUnique(doc, selector)) return selector
    }
  }

  return null
}

function segmentFor(el: Element): string {
  const tag = el.tagName.toLowerCase()
  const parent = el.parentElement
  if (!parent) return tag

  const sameTag = Array.from(parent.children).filter((child) => child.tagName === el.tagName)
  if (sameTag.length === 1) return tag
  return `${tag}:nth-of-type(${sameTag.indexOf(el) + 1})`
}

const LANDMARK_TAGS = new Set(['MAIN', 'HEADER', 'FOOTER', 'NAV', 'ASIDE'])

/**
 * Prefix a bare nth-of-type chain with its page landmark (`main`, `footer`,
 * ...) when that still matches exactly one element, so the selector tells a
 * reader which region of the page it points at.
 */
function withLandmark(el: Element, chain: string): string {
  const doc = el.ownerDocument
  let ancestor = el.parentElement
  while (ancestor && !LANDMARK_TAGS.has(ancestor.tagName)) ancestor = ancestor.parentElement
  if (!ancestor || chain.startsWith(ancestor.tagName.toLowerCase())) return chain

  const landmark = anchorSelector(ancestor, doc) ?? ancestor.tagName.toLowerCase()
  if (!isUnique(doc, landmark)) return chain
  const candidate = `${landmark} ${chain}`
  return isUnique(doc, candidate) && doc.querySelector(candidate) === el ? candidate : chain
}

/**
 * Build a short, robust CSS selector for `el`: prefer a stable id or data
 * attribute on the element or its nearest anchored ancestor, otherwise a
 * `tag:nth-of-type` chain that is just long enough to be unique, scoped to
 * its page landmark when possible.
 */
export function buildElementSelector(el: Element): string {
  const selector = buildRawSelector(el)
  return selector.startsWith('#') || selector.startsWith('[')
    ? selector
    : withLandmark(el, selector)
}

function buildRawSelector(el: Element): string {
  const doc = el.ownerDocument
  const own = anchorSelector(el, doc)
  if (own) return own

  const segments: string[] = []
  let current: Element | null = el

  while (current && current !== doc.documentElement) {
    if (current !== el) {
      const anchor = anchorSelector(current, doc)
      if (anchor) {
        const candidate = [anchor, ...segments].join(' > ')
        if (isUnique(doc, candidate)) return candidate
      }
    }

    segments.unshift(segmentFor(current))
    const candidate = segments.join(' > ')
    if (current.tagName !== 'BODY' && isUnique(doc, candidate)) return candidate
    if (current.tagName === 'BODY') return candidate

    current = current.parentElement
  }

  return segments.join(' > ')
}

/** Visible text of the element (or its image alt), collapsed and capped at 500 chars. */
export function extractElementText(el: Element): string {
  const htmlEl = el as HTMLElement
  let text = typeof htmlEl.innerText === 'string' ? htmlEl.innerText : (el.textContent ?? '')

  if (!text.trim()) {
    const labelled =
      el.getAttribute('alt') ??
      el.getAttribute('aria-label') ??
      el.getAttribute('title') ??
      el.querySelector('img[alt]')?.getAttribute('alt') ??
      ''
    text = labelled
  }

  return text.replace(/\s+/g, ' ').trim().slice(0, MAX_TARGET_TEXT)
}

export function describeElement(el: Element): string {
  const tag = el.tagName.toLowerCase()
  const names: Record<string, string> = {
    a: 'Link',
    button: 'Button',
    img: 'Image',
    h1: 'Heading',
    h2: 'Heading',
    h3: 'Heading',
    h4: 'Heading',
    p: 'Paragraph',
    section: 'Section',
    header: 'Header',
    footer: 'Footer',
    nav: 'Navigation',
    ul: 'List',
    ol: 'List',
    li: 'List item',
    figure: 'Figure',
    video: 'Video',
    iframe: 'Embed',
  }
  return `${names[tag] ?? 'Element'} <${tag}>`
}
