import { ALLOWLIST_DESCRIPTION, FILE_TYPE_DESCRIPTION } from './guardrails'
import { shortId } from './naming'
import { redactPublic } from './redact'
import type { ChangeRequest, VerificationResult } from './types'

/** Fence text so markdown, @mentions and #refs in generated text render inert. */
export function codeFence(text: string, lang = 'text'): string {
  const longest = Math.max(2, ...(text.match(/`+/g) ?? []).map((run) => run.length))
  const fence = '`'.repeat(longest + 1)
  return `${fence}${lang}\n${text}\n${fence}`
}

export interface PrBodyInput {
  request: Pick<ChangeRequest, 'id' | 'page_path' | 'target_selector'>
  siteUrl: string
  agentSummary: string
  changedFiles: string[]
  changedLines: number
  attachmentNames: string[]
  secrets?: string[]
}

/** Public metadata is deliberately fixed; generated prose and request details stay private. */
export function buildPrBody(input: PrBodyInput): string {
  const { request } = input
  const lines = [
    '## Website change request',
    '',
    `**Request:** \`${shortId(request.id)}\` — details for admins: ${input.siteUrl}/admin/requests/${request.id}`,
    '',
    'The request, agent summary, and verification evidence are available only in the authenticated admin console.',
    '',
    '## Worker checks',
    '',
    `- [x] Only allowed areas (${ALLOWLIST_DESCRIPTION.map((p) => `\`${p}\``).join(', ')}) and file types (${FILE_TYPE_DESCRIPTION}) changed — ${input.changedFiles.length} files, ${input.changedLines} lines`,
    '- [x] Agent edited an isolated checkout without dependencies; only validated files were copied into the checked checkout',
    '- [x] No credentials detected in the diff',
    '- [x] Prettier applied to changed files',
    '- [ ] All required CI jobs passed on this exact commit — see checks',
    '- [ ] Vercel preview verified in a browser (verdict is posted as a comment)',
    '- [ ] Human review and merge',
    '',
    '<details><summary>Changed files</summary>',
    '',
    ...input.changedFiles.map((f) => `- \`${f}\``),
    '',
    '</details>',
    '',
    `Submitted via /admin/requests (request ${request.id}). Generated by the change-request-agent worker; opens as a draft until CI and the preview verification both pass. Nothing deploys until a human merges this PR.`,
  ]
  return redactPublic(lines.join('\n'), input.secrets)
}

export function buildVerdictComment(
  verification: VerificationResult,
  previewUrl: string,
  adminUrl?: string
): string {
  const icon =
    verification.verdict === 'pass' ? 'PASS' : verification.verdict === 'fail' ? 'FAIL' : 'UNSURE'
  return [
    `### Preview verification: ${icon}`,
    '',
    `Preview: ${previewUrl}${verification.commit_sha ? ` (commit ${verification.commit_sha.slice(0, 7)})` : ''}`,
    '',
    'Verification details, screenshots, and recordings are private in the authenticated admin console.',
    ...(adminUrl ? [`Admin request: ${adminUrl}`] : []),
  ].join('\n')
}
