import { ALLOWLIST_DESCRIPTION } from './guardrails'
import type { ChangeRequest, VerificationResult } from './types'

/** Fence text so markdown, @mentions and #refs in user input render inert. */
export function codeFence(text: string, lang = 'text'): string {
  const longest = Math.max(2, ...(text.match(/`+/g) ?? []).map((run) => run.length))
  const fence = '`'.repeat(longest + 1)
  return `${fence}${lang}\n${text}\n${fence}`
}

export interface PrBodyInput {
  request: ChangeRequest
  agentSummary: string
  changedFiles: string[]
  changedLines: number
  attachmentNames: string[]
  checksRan: string[]
  repaired: boolean
}

/**
 * The repository is public: no requester names/emails, no attachment
 * contents — only the request fields, filenames and what the worker checked.
 */
export function buildPrBody(input: PrBodyInput): string {
  const { request } = input
  const lines = [
    '## Website change request',
    '',
    `**Title:** ${request.title.replace(/[\r\n]+/g, ' ')}`,
    `**Page:** \`${request.page_path}\``,
    request.target_selector
      ? `**Target element:** \`${request.target_selector.replace(/`/g, "'")}\``
      : null,
    '',
    '**Description**',
    '',
    codeFence(request.description),
    '',
    input.attachmentNames.length
      ? `**Attachments used:** ${input.attachmentNames.map((n) => `\`${n}\``).join(', ')}`
      : null,
    '',
    '## Agent summary',
    '',
    codeFence(input.agentSummary),
    '',
    '## Worker checks',
    '',
    `- [x] Changed files limited to ${ALLOWLIST_DESCRIPTION.map((p) => `\`${p}\``).join(', ')} (${input.changedFiles.length} files, ${input.changedLines} lines)`,
    '- [x] No credentials detected in the diff',
    '- [x] Prettier applied to changed files',
    ...input.checksRan.map(
      (c) => `- [x] \`npm run ${c}\` passed${input.repaired ? ' (after one repair round)' : ''}`
    ),
    '- [ ] Vercel preview verified in a browser (result is posted as a comment)',
    '- [ ] Human review and merge',
    '',
    '<details><summary>Changed files</summary>',
    '',
    ...input.changedFiles.map((f) => `- \`${f}\``),
    '',
    '</details>',
    '',
    `Submitted via /admin/requests (request ${request.id}). Generated by the change-request-agent worker; nothing deploys until this PR is merged.`,
  ]
  return lines.filter((line) => line !== null).join('\n')
}

export function buildVerdictComment(verification: VerificationResult, previewUrl: string): string {
  const icon =
    verification.verdict === 'pass' ? 'PASS' : verification.verdict === 'fail' ? 'FAIL' : 'UNSURE'
  return [
    `### Preview verification: ${icon}`,
    '',
    `Preview: ${previewUrl}`,
    '',
    codeFence(verification.summary),
    '',
    ...verification.checks.map(
      (c) =>
        `- [${c.ok ? 'x' : ' '}] ${c.name}${c.detail ? ` — ${c.detail.replace(/[\r\n]+/g, ' ')}` : ''}`
    ),
    '',
    'Before/after screenshots are in the admin console.',
  ].join('\n')
}
