import { ALLOWLIST_DESCRIPTION, FILE_TYPE_DESCRIPTION } from './guardrails'
import { shortId } from './naming'
import { redactPublic } from './redact'
import type { ChangeRequest, VerificationResult } from './types'

/** Fence text so markdown, @mentions and #refs in generated text render inert. */
export function codeFence(text: string, lang = 'text'): string {
  const longest = Math.max(2, ...(text.match(/`+/g) ?? []).map((run) => run.length))
  const fence = '`'.repeat(longest + 1)
  return `${fence}${lang}\n${text}\n${fence}`
}

export interface PrBodyInput {
  request: Pick<ChangeRequest, 'id' | 'page_path' | 'target_selector'>
  siteUrl: string
  agentSummary: string
  changedFiles: string[]
  changedLines: number
  attachmentNames: string[]
  checksRan: string[]
  repaired: boolean
  secrets?: string[]
}

/**
 * The repository is public. The body carries no request description, thread,
 * or requester identity: only the admin-only link, page, selector, the agent's
 * public summary, changed files and what the worker checked. Everything is
 * passed through redactPublic (and the GitHub client redacts again).
 */
export function buildPrBody(input: PrBodyInput): string {
  const { request } = input
  const selector = request.target_selector?.replace(/[`\r\n]/g, ' ')
  const lines = [
    '## Website change request',
    '',
    `**Request:** \`${shortId(request.id)}\` — details for admins: ${input.siteUrl}/admin/requests/${request.id}`,
    `**Page:** \`${request.page_path}\``,
    selector ? `**Target element:** \`${selector}\`` : null,
    input.attachmentNames.length
      ? `**Uploaded files used:** ${input.attachmentNames.map((n) => `\`${n}\``).join(', ')}`
      : null,
    '',
    '## Summary',
    '',
    codeFence(input.agentSummary),
    '',
    '## Worker checks',
    '',
    `- [x] Only allowed areas (${ALLOWLIST_DESCRIPTION.map((p) => `\`${p}\``).join(', ')}) and file types (${FILE_TYPE_DESCRIPTION}) changed — ${input.changedFiles.length} files, ${input.changedLines} lines`,
    '- [x] Agent edited an isolated checkout without dependencies; only validated files were copied into the checked checkout',
    '- [x] No credentials detected in the diff',
    '- [x] Prettier applied to changed files',
    ...input.checksRan.map(
      (c) => `- [x] \`npm run ${c}\` passed${input.repaired ? ' (after one repair round)' : ''}`
    ),
    '- [ ] Vercel preview verified in a browser (result is posted as a comment)',
    '- [ ] Human review and merge',
    '',
    '<details><summary>Changed files</summary>',
    '',
    ...input.changedFiles.map((f) => `- \`${f}\``),
    '',
    '</details>',
    '',
    `Submitted via /admin/requests (request ${request.id}). Generated by the change-request-agent worker; nothing deploys until this PR is merged.`,
  ]
  return redactPublic(lines.filter((line) => line !== null).join('\n'), input.secrets)
}

export function buildVerdictComment(verification: VerificationResult, previewUrl: string): string {
  const icon =
    verification.verdict === 'pass' ? 'PASS' : verification.verdict === 'fail' ? 'FAIL' : 'UNSURE'
  return [
    `### Preview verification: ${icon}`,
    '',
    `Preview: ${previewUrl}${verification.commit_sha ? ` (commit ${verification.commit_sha.slice(0, 7)})` : ''}`,
    '',
    codeFence(verification.summary),
    '',
    ...verification.checks.map(
      (c) =>
        `- [${c.ok ? 'x' : ' '}] ${c.name}${c.detail ? ` — ${c.detail.replace(/[\r\n]+/g, ' ')}` : ''}`
    ),
    '',
    'Before/after screenshots are in the admin console.',
  ].join('\n')
}
